### PR TITLE
Fixes #28726 - pin rsec

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
Please merge https://github.com/theforeman/smart_proxy_dhcp_remote_isc/pull/2 and rebase on top of it :)

**Comment by ekohl** [comment]
Actually included this since I was already pinning it in the gemspec.

**Comment by mmoll** [comment]
I see... I'd rather say cherry-pick my change into #2 and find somebody with merge permissions :smile:.

**Comment by ekohl** [comment]
If you ack the PR, I don't have an issue merging my own PR :)

**Pull request closed without merging**
